version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_for_Spring_GitHub
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
  

  student-service:
    build: ./student-service
    container_name: student-service
    depends_on:
      - mysql
      - grade-service # for feign client to work
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/DB_for_Spring_GitHub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8080:8080
    # networks:
    #   - mynetwork

  grade-service:
    build: ./grade-service #this will build the image
    container_name: grade-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/DB_for_Spring_GitHub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8081:8081 # 8081:8081 is original
    # networks:
    #   - mynetwork

# networks:
#   mynetwork:
#     driver: bridge
#     attachable: true

volumes:
  mysql_data: